-- Generated by matugen from the current wallpaper — do not hand-edit.
-- Required by hyprland.lua as: local colors = require("colors")
return {
    active_border = {
        colors = { "rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)" },
        angle = 45,
    },
    inactive_border = "rgba({{colors.outline.default.hex_stripped}}aa)",
}
