#!/usr/bin/env bash
# Bootstrap script for fawdots on a fresh Arch/Hyprland install.
# Safe to re-run.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

PACMAN_PKGS=(stow hyprpaper hypridle hyprlock pipewire-pulse wireplumber grim slurp wl-clipboard
	satty hyprshot xdg-user-dirs waybar networkmanager network-manager-applet bluez
	bluez-utils blueman pavucontrol ttf-nerd-fonts-symbols ttf-adwaitamono-nerd dunst matugen
	kitty adwaita-fonts adw-gtk-theme nautilus polkit-kde-agent cliphist swayosd hyprpicker
	wf-recorder hyprlauncher playerctl brightnessctl xdg-desktop-portal
	xdg-desktop-portal-hyprland xdg-desktop-portal-gtk python-gobject gtk3 gtk-layer-shell
	ttf-ubuntu-font-family)
AUR_PKGS=(waypaper nwg-launchers)

echo "==> Installing pacman packages: ${PACMAN_PKGS[*]}"
sudo pacman -S --needed "${PACMAN_PKGS[@]}"

if [ "${#AUR_PKGS[@]}" -gt 0 ]; then
	if ! command -v yay >/dev/null 2>&1; then
		echo "==> yay not found; bootstrapping it from AUR"
		sudo pacman -S --needed base-devel git
		yay_build_dir="$(mktemp -d)"
		git clone https://aur.archlinux.org/yay.git "$yay_build_dir/yay"
		(cd "$yay_build_dir/yay" && makepkg -si)
		rm -rf "$yay_build_dir"
	fi
	echo "==> Installing AUR packages: ${AUR_PKGS[*]}"
	yay -S --needed "${AUR_PKGS[@]}"
fi

echo "==> Enabling NetworkManager and bluetooth"
sudo systemctl enable --now NetworkManager bluetooth

echo "==> Stowing packages into \$HOME"
for pkg in */; do
	pkg="${pkg%/}"
	[[ "$pkg" == ".git" ]] && continue
	if stow --restow --target="$HOME" "$pkg"; then
		echo "    stowed $pkg"
	else
		# A real (non-symlink) file already exists at the target — e.g. a
		# freshly-autogenerated ~/.config/hypr/hyprland.lua from Hyprland's
		# own first launch, before this repo ever touched the machine.
		# --adopt pulls the existing file into the repo (as a symlink); we
		# immediately discard what it pulled in via git checkout so the
		# repo's tracked content — not the machine's autogenerated default —
		# is what ends up live. Only touches this one package.
		echo "    $pkg conflicted with an existing file; adopting and restoring tracked version"
		stow --adopt --restow --target="$HOME" "$pkg"
		git checkout -- "$pkg"
		echo "    stowed $pkg (resolved conflict)"
	fi
done

chmod +x ~/.local/bin/matugen-apply ~/.local/bin/theme-toggle ~/.local/bin/record-toggle \
	~/.local/bin/hypr-monitor ~/.local/bin/waybar-clock ~/.local/bin/waybar-calendar \
	~/.local/bin/nwggrid-launch

echo "==> Setting up XDG user directories (~/Pictures, ~/Downloads, etc.)"
xdg-user-dirs-update
mkdir -p ~/Pictures/Wallpapers

if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
	echo "==> Syncing theme colors from the current wallpaper (re-applies template changes too,"
	echo "    e.g. after a git pull — without resetting which wallpaper/mode is active)"
	# No wallpaper arg: matugen-apply resolves the last one waypaper picked.
	# Falls back to the bundled default only on a genuine first run, where
	# nothing has ever been picked yet (matugen-apply exits 1 in that case).
	~/.local/bin/matugen-apply || ~/.local/bin/matugen-apply /usr/share/hypr/wall2.png

	echo "==> Reloading Hyprland config and restarting waybar so this run's changes actually"
	echo "    show up live, not just on disk (stow updates symlinks, not running processes)"
	hyprctl reload
	pkill -x waybar 2>/dev/null || true
	sleep 0.5
	(waybar >/dev/null 2>&1 &disown)
else
	# The hyprland-colors template's post_hook runs `hyprctl reload`, which
	# fails with nothing to abort install.sh (set -e) if there's no live
	# Hyprland session to reload — e.g. running this before ever logging in.
	echo "==> Not running inside Hyprland — skipping theme sync and waybar restart."
	echo "    After logging into Hyprland, run: ~/.local/bin/matugen-apply /usr/share/hypr/wall2.png"
fi

echo "==> Done. Log out/in (or restart Hyprland) to pick up autostart-only changes (new"
echo "    exec-once entries, etc.) — everything else just applied live above."
echo "    Add wallpapers to ~/Pictures/Wallpapers, then SUPER+W opens waypaper to pick one"
echo "    (colors auto-sync to waybar/hyprlock/kitty/GTK/borders on every change)."
echo "    SUPER+SHIFT+D toggles light/dark mode for the current wallpaper."
echo "    SUPER+SHIFT+V: clipboard history | SUPER+SHIFT+C: color picker | SUPER+SHIFT+R: record toggle"
