#!/usr/bin/env bash
# Bootstrap script for fawdots on a fresh Arch/Hyprland install.
# Safe to re-run.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# --- cosmetics ---------------------------------------------------------
# Degrades to plain text automatically when not on a real terminal (piped
# output, CI, NO_COLOR set) or when tput/colors aren't available — real
# command output (pacman/yay/sudo prompts) is never touched by any of this,
# only the "==>" step headers we print ourselves.
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && tput setaf 1 >/dev/null 2>&1; then
	c_reset=$(tput sgr0)
	c_bold=$(tput bold)
	c_dim=$(tput dim)
	c_cyan=$(tput setaf 6)
	c_blue=$(tput setaf 4)
	c_magenta=$(tput setaf 5)
	c_green=$(tput setaf 2)
	animate=1
else
	c_reset="" c_bold="" c_dim="" c_cyan="" c_blue="" c_magenta="" c_green=""
	animate=0
fi

step() {
	printf '\n%s%s==>%s %s%s%s\n' "$c_bold" "$c_green" "$c_reset" "$c_bold" "$*" "$c_reset"
}

note() {
	printf '%s    %s%s\n' "$c_dim" "$*" "$c_reset"
}

banner=(
	"█████  ███  █   █ ████   ███  █████  ████ "
	"█     █   █ █   █ █   █ █   █   █   █     "
	"███   █████ █ █ █ █   █ █   █   █    ███  "
	"█     █   █ ██ ██ █   █ █   █   █       █ "
	"█     █   █ █   █ ████   ███    █   ████  "
)
banner_colors=("$c_cyan" "$c_blue" "$c_magenta" "$c_blue" "$c_cyan")

for i in "${!banner[@]}"; do
	printf '%s%s%s%s\n' "$c_bold" "${banner_colors[$i]}" "${banner[$i]}" "$c_reset"
	[ "$animate" -eq 1 ] && sleep 0.05
done
printf '%s  Hyprland dotfiles installer%s\n' "$c_dim" "$c_reset"

PACMAN_PKGS=(stow swaybg hypridle hyprlock pipewire-pulse wireplumber grim slurp wl-clipboard
	satty hyprshot xdg-user-dirs waybar networkmanager network-manager-applet bluez
	bluez-utils blueman pavucontrol ttf-nerd-fonts-symbols ttf-adwaitamono-nerd dunst matugen discord
	kitty adwaita-fonts adw-gtk-theme nautilus polkit-kde-agent cliphist swayosd hyprpicker
	wf-recorder hyprlauncher playerctl brightnessctl xdg-desktop-portal
	xdg-desktop-portal-hyprland xdg-desktop-portal-gtk python-gobject gtk3 gtk-layer-shell
	ttf-ubuntu-font-family ttf-ubuntu-nerd imagemagick zsh zsh-autosuggestions zsh-syntax-highlighting)
AUR_PKGS=(waypaper nwg-launchers oh-my-zsh-git neofetch mpvpaper brave-bin visual-studio-code-bin)

step "Installing pacman packages"
note "${PACMAN_PKGS[*]}"
sudo pacman -S --needed "${PACMAN_PKGS[@]}"

if [ "${#AUR_PKGS[@]}" -gt 0 ]; then
	if ! command -v yay >/dev/null 2>&1; then
		step "yay not found; bootstrapping it from AUR"
		sudo pacman -S --needed base-devel git
		yay_build_dir="$(mktemp -d)"
		git clone https://aur.archlinux.org/yay.git "$yay_build_dir/yay"
		(cd "$yay_build_dir/yay" && makepkg -si)
		rm -rf "$yay_build_dir"
	fi
	step "Installing AUR packages"
	note "${AUR_PKGS[*]}"
	yay -S --needed "${AUR_PKGS[@]}"
fi

step "Enabling NetworkManager and bluetooth"
sudo systemctl enable --now NetworkManager bluetooth

step "Stowing packages into \$HOME"
for pkg in */; do
	pkg="${pkg%/}"
	[[ "$pkg" == ".git" ]] && continue
	if stow --restow --target="$HOME" "$pkg"; then
		printf '    %sstowed %s%s\n' "$c_green" "$pkg" "$c_reset"
	else
		# A real (non-symlink) file already exists at the target — e.g. a
		# freshly-autogenerated ~/.config/hypr/hyprland.lua from Hyprland's
		# own first launch, before this repo ever touched the machine.
		# --adopt pulls the existing file into the repo (as a symlink); we
		# immediately discard what it pulled in via git checkout so the
		# repo's tracked content — not the machine's autogenerated default —
		# is what ends up live. Only touches this one package.
		note "$pkg conflicted with an existing file; adopting and restoring tracked version"
		stow --adopt --restow --target="$HOME" "$pkg"
		git checkout -- "$pkg"
		printf '    %sstowed %s (resolved conflict)%s\n' "$c_green" "$pkg" "$c_reset"
	fi
done

chmod +x ~/.local/bin/matugen-apply ~/.local/bin/theme-toggle ~/.local/bin/record-toggle \
	~/.local/bin/hypr-monitor ~/.local/bin/waybar-clock ~/.local/bin/waybar-calendar \
	~/.local/bin/nwggrid-launch ~/.local/bin/neofetch-sticker

step "Setting up XDG user directories (~/Pictures, ~/Downloads, etc.)"
xdg-user-dirs-update
mkdir -p ~/Pictures/Wallpapers ~/Pictures/Stickers

if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
	step "Syncing theme colors from the current wallpaper"
	note "re-applies template changes too (e.g. after a git pull) without resetting"
	note "which wallpaper/mode is active"
	# No wallpaper arg: matugen-apply resolves the last one waypaper picked.
	# Falls back to the bundled default only on a genuine first run, where
	# nothing has ever been picked yet (matugen-apply exits 1 in that case).
	~/.local/bin/matugen-apply || ~/.local/bin/matugen-apply /usr/share/hypr/wall2.png

	step "Reloading Hyprland config and restarting waybar"
	note "so this run's changes actually show up live, not just on disk"
	note "(stow updates symlinks, not running processes)"
	hyprctl reload
	pkill -x waybar 2>/dev/null || true
	sleep 0.5
	(waybar >/dev/null 2>&1 &disown)
else
	# The hyprland-colors template's post_hook runs `hyprctl reload`, which
	# fails with nothing to abort install.sh (set -e) if there's no live
	# Hyprland session to reload — e.g. running this before ever logging in.
	step "Not running inside Hyprland — skipping theme sync and waybar restart"
	note "After logging into Hyprland, run: ~/.local/bin/matugen-apply /usr/share/hypr/wall2.png"
fi

step "Done"
note "Log out/in (or restart Hyprland) to pick up autostart-only changes (new"
note "exec-once entries, etc.) — everything else just applied live above."
note "Add wallpapers to ~/Pictures/Wallpapers, then SUPER+W opens waypaper to pick one"
note "(colors auto-sync to waybar/hyprlock/kitty/GTK/borders on every change)."
note "SUPER+SHIFT+D toggles light/dark mode for the current wallpaper."
note "SUPER+SHIFT+V: clipboard history | SUPER+SHIFT+C: color picker | SUPER+SHIFT+R: record toggle"
